# Project information
site_name: "ED:Journal API"
site_description: "Documentation for Elite Dangerous journal API"
site_author: "ROMVoid95"
site_url: "https://romvoid95.github.io/EDJournalAPI/"

# Copyright
copyright: "&copy; 2023 ROMVoid95"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/ROMVoid95/EDJournalAPI"
edit_uri: "https://github.com/ROMVoid95/EDJournalAPI/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "blue"
    accent: "blue"
  features:
    - tabs
  #font:
  #text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/ROMVoid95"

nav:
  - "Introduction": "index.md"
  - "File Format": "file-format.md"
  - "Startup": "startup.md"
  - "Travel": "travel.md"
  - "Combat": "combat.md"
  - "Exploration": "exploration.md"
  - "Trade": "trade.md"
  - "Station Services": "station-services.md"
  - "Powerplay": "powerplay.md"
  - "Squadrons": "squadrons.md"
  - "Fleet Carriers": "fleetcarriers.md"
  - "New in Odyssey": "new-in-oddesey.md"
  - "Other Events": "misc-events.md"
  - "Status File": "status-file.md"
  - "Appendix": "appendix.md"